## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

## LEDs
#set_property PACKAGE_PIN U16 [get_ports {pass}]
#set_property IOSTANDARD LVCMOS33 [get_ports {pass}]

## Switches
#set_property PACKAGE_PIN V17 [get_ports hint]
#set_property IOSTANDARD LVCMOS33 [get_ports hint]

## Buttons
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
#set_property PACKAGE_PIN T17 [get_ports start]
#set_property IOSTANDARD LVCMOS33 [get_ports start]

# Switches
set_property PACKAGE_PIN V17 [get_ports {cheat}]
set_property IOSTANDARD LVCMOS33 [get_ports {cheat}]
# set_property PACKAGE_PIN V16 [get_ports {error_bit_input[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[1]}]
# set_property PACKAGE_PIN W16 [get_ports {error_bit_input[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[2]}]
# set_property PACKAGE_PIN W17 [get_ports {error_bit_input[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[3]}]
# set_property PACKAGE_PIN W15 [get_ports {error_bit_input[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[4]}]
# set_property PACKAGE_PIN V15 [get_ports {error_bit_input[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[5]}]
# set_property PACKAGE_PIN W14 [get_ports {error_bit_input[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[6]}]
# set_property PACKAGE_PIN W13 [get_ports {error_bit_input[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[7]}]
# set_property PACKAGE_PIN V2 [get_ports {error_bit_input[8]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[8]}]
# set_property PACKAGE_PIN T3 [get_ports {error_bit_input[9]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {error_bit_input[9]}]
# set_property PACKAGE_PIN T2 [get_ports {raw_data[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[0]}]
# set_property PACKAGE_PIN R3 [get_ports {raw_data[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[1]}]
# set_property PACKAGE_PIN W2 [get_ports {raw_data[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[2]}]
# set_property PACKAGE_PIN U1 [get_ports {raw_data[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[3]}]
# set_property PACKAGE_PIN T1 [get_ports {raw_data[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {raw_data[4]}]
# set_property PACKAGE_PIN R2 [get_ports {rst}]
# set_property IOSTANDARD LVCMOS33 [get_ports {rst}]

## VGA Connector
set_property PACKAGE_PIN G19 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN H19 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN J19 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN N19 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN N18 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN L18 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN K18 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN J18 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN J17 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN H17 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN G17 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN D17 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN P19 [get_ports HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports HSYNC]
set_property PACKAGE_PIN R19 [get_ports VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports VSYNC]


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

## USB HID (PS/2)
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property PULLUP true [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property PULLUP true [get_ports PS2_DATA]


